swayimg.text.set_font('monospace')
swayimg.text.set_size(18)

swayimg.viewer.set_default_scale('fit')

swayimg.viewer.on_key('0', function()
  swayimg.viewer.set_abs_scale(1)
end)
swayimg.viewer.on_key('q', function()
  swayimg.exit()
end)
swayimg.viewer.on_key('p', function()
  swayimg.viewer.switch_image('prev')
end)
swayimg.viewer.on_key('n', function()
  swayimg.viewer.switch_image('next')
end)

swayimg.gallery.on_key('q', function()
  swayimg.exit()
end)
swayimg.gallery.on_key('p', function()
  swayimg.gallery.switch_image('left')
end)
swayimg.gallery.on_key('n', function()
  swayimg.gallery.switch_image('right')
end)
swayimg.gallery.on_key('h', function()
  swayimg.gallery.switch_image('left')
end)
swayimg.gallery.on_key('j', function()
  swayimg.gallery.switch_image('down')
end)
swayimg.gallery.on_key('k', function()
  swayimg.gallery.switch_image('up')
end)
swayimg.gallery.on_key('l', function()
  swayimg.gallery.switch_image('right')
end)
