[main]
font=JetBrains Mono:size=10,Symbols Nerd Font Mono:size=10
include=/usr/share/foot/themes/kitty
pad = 0x0
gamma-correct-blending=yes

[tweak]
surface-bit-depth=8-bit

[text-bindings]
\x1b\x0d=Shift+Return

# vim: ft=conf
