#!/usr/bin/env bash

monitor="HDMI-A-1"
monitorv2_keyword="monitorv2[$monitor]:mode"
resolution="2560x1440"

high_refresh_rate=240
hdr_compatible_refresh_rate=144

refresh_rate="$(hyprctl monitors -j | jq ".[] | select(.name == \"$monitor\") | .refreshRate" | xargs printf "%.0f\n")"

if [[ "$refresh_rate" == "$hdr_compatible_refresh_rate" ]]; then
  hyprctl keyword "$monitorv2_keyword" "$resolution@$high_refresh_rate"
  notify-send "$monitor set to $high_refresh_rate Hz"
else
  hyprctl keyword "$monitorv2_keyword" "$resolution@$hdr_compatible_refresh_rate"
  notify-send "$monitor set to $hdr_compatible_refresh_rate Hz"
fi
