#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

xrdb -load ~/.Xresources
udiskie &
nm-applet &
earlyoom -n -m 5 -s 5 &
dunst &
"$HOME"/.config/dunst/battery_notification &
picom &
nitrogen --restore &
"$HOME"/.config/polybar/launch &
opensnitch-ui &

"$HOME/.config/bspwm/setup-monitors"

bspc config border_width           2
bspc config window_gap             0

bspc config split_ratio            0.50
bspc config borderless_monocle     false
bspc config gapless_monocle        false
bspc config center_pseudo_tiled    true
bspc config focus_follows_pointer  true
bspc config top_padding            14

# THESE COLORS ARE CHANGED WITH chtheme
bspc config focused_border_color   "#cf3704"
bspc config presel_feedback_color  "#cf3704"
bspc config normal_border_color    "#161616"

# use Xprop to get the window class
bspc config external_rules_command "$HOME/.config/bspwm/external-rules"
bspc config ignore_ewmh_focus on

bspc rule -a Screenkey manage=off
bspc rule -a Sxiv state='floating'
bspc rule -a Brave-browser:crx_nkbihfbeogaeaoehlefnkodbefgpgknn state='floating' # MetaMask extension
bspc rule -a Brave-browser:crx_bfnaelmomeimhlpmgjnjophhpkkoljpa state='floating' # Phantom extension

bspc rule -a discord desktop=2
bspc rule -a Slack desktop=2
bspc rule -a Element desktop=4
bspc rule -a Element-Nightly desktop=4
bspc rule -a steam desktop=5
bspc rule -a "SDL Application" desktop=5 # Steam
bspc rule -a Spotify desktop=6
