#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrdb -load ~/.Xresources
udiskie &
nm-applet &
# earlyoom -n -m 5 -s 5 & # Probably not needed anymore
dunst &
"$HOME"/.config/dunst/battery_notification &
picom &
nitrogen --restore &
"$HOME"/.config/polybar/launch.sh &

# Double screen setup
if [[ $(xrandr -q | grep 'HDMI-0 connected') ]]; then
  xrandr \
    --output HDMI-0 --primary --mode 1920x1080 --rotate normal -r 60 \
    --output DP-4 --mode 1920x1080 --rotate normal --right-of HDMI-0 -r 60

  bspc monitor HDMI-0 -d 1 3 5 7 9
  bspc monitor DP-4   -d 2 4 6 8 10
fi

bspc config border_width           2
bspc config window_gap             0

bspc config split_ratio            0.50
bspc config borderless_monocle     false
bspc config gapless_monocle        false
bspc config center_pseudo_tiled    true
bspc config focus_follows_pointer  true
bspc config top_padding            14

# THESE COLORS ARE CHANGED WITH chtheme
bspc config focused_border_color   "#aa0000"
bspc config presel_feedback_color  "#aa0000"
bspc config normal_border_color    "#161616"

# use Xprop to get the window class
bspc config external_rules_command "$HOME/bin/bspwm-external-rules"
bspc config ignore_ewmh_focus on
bspc rule -a Screenkey manage=off
bspc rule -a Sxiv state='floating'
bspc rule -a Brave-browser:crx_nkbihfbeogaeaoehlefnkodbefgpgknn state='floating' # MetaMask extension
bspc rule -a Brave-browser:crx_bfnaelmomeimhlpmgjnjophhpkkoljpa state='floating' # Phantom extension
bspc rule -a discord desktop=2
bspc rule -a Element desktop=4
bspc rule -a Element-Nightly desktop=4
bspc rule -a Spotify desktop=6
