name: Update
on:
  schedule:
    - cron: "0 12 * * 5" # Every Friday, 12 PM UTC
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-flake:
    name: Update Flake Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org https://nix-community.cachix.org https://hyprland.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=
      - name: Update flake inputs
        run: nix flake update
      - name: Run flake checks
        run: nix flake check
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update flake.lock"
          file_pattern: flake.lock
